// icons.js — набор иконок-плиток категорий (SVG-спрайт icons/ui-icons.svg).
// Каждая запись: key, русское имя, группа (цвет), symbol — id в спрайте,
// kind — тип категории ("expense" | "income").
export const CATEGORY_ICONS = [
  // --- Расходы (50) ---
  { key: "rent-mortgage", label: "Аренда / ипотека", group: "housing", groupLabel: "Жильё и коммунальные услуги", symbol: "tile-rent-mortgage", color: "#84542A", colorDark: "#603B1A", kind: "expense" },
  { key: "utilities", label: "Коммунальные услуги", group: "housing", groupLabel: "Жильё и коммунальные услуги", symbol: "tile-utilities", color: "#84542A", colorDark: "#603B1A", kind: "expense" },
  { key: "internet-tv", label: "Интернет и ТВ", group: "housing", groupLabel: "Жильё и коммунальные услуги", symbol: "tile-internet-tv", color: "#84542A", colorDark: "#603B1A", kind: "expense" },
  { key: "cleaning", label: "Уборка и клининг", group: "housing", groupLabel: "Жильё и коммунальные услуги", symbol: "tile-cleaning", color: "#84542A", colorDark: "#603B1A", kind: "expense" },
  { key: "groceries", label: "Продукты (дом)", group: "food", groupLabel: "Питание", symbol: "tile-groceries", color: "#993229", colorDark: "#74221A", kind: "expense" },
  { key: "cafe-restaurants", label: "Кафе и рестораны", group: "food", groupLabel: "Питание", symbol: "tile-cafe-restaurants", color: "#993229", colorDark: "#74221A", kind: "expense" },
  { key: "fast-food", label: "Фастфуд и стритфуд", group: "food", groupLabel: "Питание", symbol: "tile-fast-food", color: "#993229", colorDark: "#74221A", kind: "expense" },
  { key: "coffee-snacks", label: "Кофе с собой / снеки", group: "food", groupLabel: "Питание", symbol: "tile-coffee-snacks", color: "#993229", colorDark: "#74221A", kind: "expense" },
  { key: "public-transport", label: "Общественный транспорт", group: "transport", groupLabel: "Транспорт и поездки", symbol: "tile-public-transport", color: "#305A88", colorDark: "#1F4165", kind: "expense" },
  { key: "taxi-carsharing", label: "Такси / каршеринг", group: "transport", groupLabel: "Транспорт и поездки", symbol: "tile-taxi-carsharing", color: "#305A88", colorDark: "#1F4165", kind: "expense" },
  { key: "personal-car", label: "Личный автомобиль", group: "transport", groupLabel: "Транспорт и поездки", symbol: "tile-personal-car", color: "#305A88", colorDark: "#1F4165", kind: "expense" },
  { key: "car-maintenance", label: "Ремонт и ТО авто", group: "transport", groupLabel: "Транспорт и поездки", symbol: "tile-car-maintenance", color: "#305A88", colorDark: "#1F4165", kind: "expense" },
  { key: "car-insurance", label: "Страховка авто", group: "transport", groupLabel: "Транспорт и поездки", symbol: "tile-car-insurance", color: "#305A88", colorDark: "#1F4165", kind: "expense" },
  { key: "flights", label: "Авиаперелёты", group: "transport", groupLabel: "Транспорт и поездки", symbol: "tile-flights", color: "#305A88", colorDark: "#1F4165", kind: "expense" },
  { key: "train-bus-longdistance", label: "Ж/д и автобусы дальнего следования", group: "transport", groupLabel: "Транспорт и поездки", symbol: "tile-train-bus-longdistance", color: "#305A88", colorDark: "#1F4165", kind: "expense" },
  { key: "pharmacy", label: "Аптеки и лекарства", group: "health", groupLabel: "Здоровье и уход", symbol: "tile-pharmacy", color: "#2C775C", colorDark: "#1B5540", kind: "expense" },
  { key: "doctors-diagnostics", label: "Врачи и диагностика", group: "health", groupLabel: "Здоровье и уход", symbol: "tile-doctors-diagnostics", color: "#2C775C", colorDark: "#1B5540", kind: "expense" },
  { key: "health-insurance", label: "ДМС / полисы", group: "health", groupLabel: "Здоровье и уход", symbol: "tile-health-insurance", color: "#2C775C", colorDark: "#1B5540", kind: "expense" },
  { key: "sport-fitness", label: "Спорт и фитнес", group: "health", groupLabel: "Здоровье и уход", symbol: "tile-sport-fitness", color: "#2C775C", colorDark: "#1B5540", kind: "expense" },
  { key: "sports-gear", label: "Спортивный инвентарь", group: "health", groupLabel: "Здоровье и уход", symbol: "tile-sports-gear", color: "#2C775C", colorDark: "#1B5540", kind: "expense" },
  { key: "clothing-shoes", label: "Одежда, обувь, аксессуары", group: "style", groupLabel: "Одежда и внешность", symbol: "tile-clothing-shoes", color: "#8A3865", colorDark: "#69264B", kind: "expense" },
  { key: "salon-beauty", label: "Салонная красота", group: "style", groupLabel: "Одежда и внешность", symbol: "tile-salon-beauty", color: "#8A3865", colorDark: "#69264B", kind: "expense" },
  { key: "cosmetics-perfume", label: "Косметика и парфюм", group: "style", groupLabel: "Одежда и внешность", symbol: "tile-cosmetics-perfume", color: "#8A3865", colorDark: "#69264B", kind: "expense" },
  { key: "hygiene-household-chem", label: "Гигиена и быт. химия", group: "style", groupLabel: "Одежда и внешность", symbol: "tile-hygiene-household-chem", color: "#8A3865", colorDark: "#69264B", kind: "expense" },
  { key: "courses-training", label: "Курсы и тренинги", group: "education", groupLabel: "Саморазвитие и образование", symbol: "tile-courses-training", color: "#43368C", colorDark: "#2F246A", kind: "expense" },
  { key: "books-magazines", label: "Книги и журналы", group: "education", groupLabel: "Саморазвитие и образование", symbol: "tile-books-magazines", color: "#43368C", colorDark: "#2F246A", kind: "expense" },
  { key: "tutors-mentors", label: "Репетиторы / менторы", group: "education", groupLabel: "Саморазвитие и образование", symbol: "tile-tutors-mentors", color: "#43368C", colorDark: "#2F246A", kind: "expense" },
  { key: "cinema-theatre-concerts", label: "Кино, театры, концерты", group: "leisure", groupLabel: "Досуг и развлечения", symbol: "tile-cinema-theatre-concerts", color: "#96782C", colorDark: "#725A1D", kind: "expense" },
  { key: "hobbies-games", label: "Хобби и игры", group: "leisure", groupLabel: "Досуг и развлечения", symbol: "tile-hobbies-games", color: "#96782C", colorDark: "#725A1D", kind: "expense" },
  { key: "alcohol-hookah", label: "Алкоголь и кальяны", group: "leisure", groupLabel: "Досуг и развлечения", symbol: "tile-alcohol-hookah", color: "#96782C", colorDark: "#725A1D", kind: "expense" },
  { key: "travel-tours", label: "Путешествия и туры", group: "leisure", groupLabel: "Досуг и развлечения", symbol: "tile-travel-tours", color: "#96782C", colorDark: "#725A1D", kind: "expense" },
  { key: "gifts-celebrations", label: "Подарки и поздравления", group: "family", groupLabel: "Семья и личные отношения", symbol: "tile-gifts-celebrations", color: "#3F7836", colorDark: "#2A5823", kind: "expense" },
  { key: "kids-needs", label: "Детские нужды", group: "family", groupLabel: "Семья и личные отношения", symbol: "tile-kids-needs", color: "#3F7836", colorDark: "#2A5823", kind: "expense" },
  { key: "pets", label: "Домашние животные", group: "family", groupLabel: "Семья и личные отношения", symbol: "tile-pets", color: "#3F7836", colorDark: "#2A5823", kind: "expense" },
  { key: "taxes", label: "Налоги", group: "finance", groupLabel: "Финансовые обязательства", symbol: "tile-taxes", color: "#2A2F51", colorDark: "#161A31", kind: "expense" },
  { key: "loans-interest", label: "Кредиты и проценты", group: "finance", groupLabel: "Финансовые обязательства", symbol: "tile-loans-interest", color: "#2A2F51", colorDark: "#161A31", kind: "expense" },
  { key: "pension-investments", label: "Пенсионные и инвестиционные взносы", group: "finance", groupLabel: "Финансовые обязательства", symbol: "tile-pension-investments", color: "#2A2F51", colorDark: "#161A31", kind: "expense" },
  { key: "home-repair-construction", label: "Ремонт и строительство", group: "home_repair", groupLabel: "Быт и ремонт", symbol: "tile-home-repair-construction", color: "#646D2C", colorDark: "#454B1B", kind: "expense" },
  { key: "furniture-appliances", label: "Покупка мебели и техники", group: "home_repair", groupLabel: "Быт и ремонт", symbol: "tile-furniture-appliances", color: "#646D2C", colorDark: "#454B1B", kind: "expense" },
  { key: "electronics-repair-services", label: "Сервисы и ремонт электроники", group: "home_repair", groupLabel: "Быт и ремонт", symbol: "tile-electronics-repair-services", color: "#646D2C", colorDark: "#454B1B", kind: "expense" },
  { key: "software-subscriptions", label: "Подписки на софт и сервисы", group: "digital", groupLabel: "Цифровые услуги", symbol: "tile-software-subscriptions", color: "#296670", colorDark: "#19464D", kind: "expense" },
  { key: "mobile-apps-games", label: "Приложения и игры", group: "digital", groupLabel: "Цифровые услуги", symbol: "tile-mobile-apps-games", color: "#296670", colorDark: "#19464D", kind: "expense" },
  { key: "life-property-insurance", label: "Страховка жизни / имущества", group: "mandatory", groupLabel: "Прочие обязательные", symbol: "tile-life-property-insurance", color: "#52396A", colorDark: "#38244C", kind: "expense" },
  { key: "bank-fees", label: "Банковские комиссии", group: "mandatory", groupLabel: "Прочие обязательные", symbol: "tile-bank-fees", color: "#52396A", colorDark: "#38244C", kind: "expense" },
  { key: "membership-fees", label: "Членские взносы", group: "mandatory", groupLabel: "Прочие обязательные", symbol: "tile-membership-fees", color: "#52396A", colorDark: "#38244C", kind: "expense" },
  { key: "unexpected-expenses", label: "Непредвиденные расходы", group: "buffer", groupLabel: "Буферные категории", symbol: "tile-unexpected-expenses", color: "#726B65", colorDark: "#5B5249", kind: "expense" },
  { key: "miscellaneous", label: "Прочее", group: "buffer", groupLabel: "Буферные категории", symbol: "tile-miscellaneous", color: "#726B65", colorDark: "#5B5249", kind: "expense" },
  { key: "charity-donations", label: "Благотворительность и пожертвования", group: "bonus", groupLabel: "Дополнительные умные категории", symbol: "tile-charity-donations", color: "#7A297A", colorDark: "#571957", kind: "expense" },
  { key: "fines-penalties", label: "Штрафы и пени", group: "bonus", groupLabel: "Дополнительные умные категории", symbol: "tile-fines-penalties", color: "#7A297A", colorDark: "#571957", kind: "expense" },
  { key: "transfers-to-family", label: "Переводы родственникам", group: "bonus", groupLabel: "Дополнительные умные категории", symbol: "tile-transfers-to-family", color: "#7A297A", colorDark: "#571957", kind: "expense" },
  // --- Доходы (34) ---
  { key: "salary", label: "Зарплата", group: "main_income", groupLabel: "Основная деятельность", symbol: "tile-salary", color: "#2F7F2F", colorDark: "#1E5C1E", kind: "income" },
  { key: "bonus", label: "Премия / Бонус", group: "main_income", groupLabel: "Основная деятельность", symbol: "tile-bonus", color: "#2F7F2F", colorDark: "#1E5C1E", kind: "income" },
  { key: "overtime", label: "Овертайм", group: "main_income", groupLabel: "Основная деятельность", symbol: "tile-overtime", color: "#2F7F2F", colorDark: "#1E5C1E", kind: "income" },
  { key: "tips", label: "Чаевые", group: "main_income", groupLabel: "Основная деятельность", symbol: "tile-tips", color: "#2F7F2F", colorDark: "#1E5C1E", kind: "income" },
  { key: "business-income", label: "Бизнес", group: "business", groupLabel: "Бизнес и предпринимательство", symbol: "tile-business-income", color: "#32511F", colorDark: "#1B2E10", kind: "income" },
  { key: "freelance", label: "Фриланс / Проекты", group: "business", groupLabel: "Бизнес и предпринимательство", symbol: "tile-freelance", color: "#32511F", colorDark: "#1B2E10", kind: "income" },
  { key: "services-income", label: "Услуги", group: "business", groupLabel: "Бизнес и предпринимательство", symbol: "tile-services-income", color: "#32511F", colorDark: "#1B2E10", kind: "income" },
  { key: "goods-sale", label: "Продажа товаров", group: "business", groupLabel: "Бизнес и предпринимательство", symbol: "tile-goods-sale", color: "#32511F", colorDark: "#1B2E10", kind: "income" },
  { key: "investments", label: "Инвестиции", group: "passive", groupLabel: "Пассивный доход и финансы", symbol: "tile-investments", color: "#2F6B74", colorDark: "#1E4C52", kind: "income" },
  { key: "dividends", label: "Дивиденды", group: "passive", groupLabel: "Пассивный доход и финансы", symbol: "tile-dividends", color: "#2F6B74", colorDark: "#1E4C52", kind: "income" },
  { key: "deposit-interest", label: "Проценты по вкладу", group: "passive", groupLabel: "Пассивный доход и финансы", symbol: "tile-deposit-interest", color: "#2F6B74", colorDark: "#1E4C52", kind: "income" },
  { key: "crypto", label: "Криптовалюта", group: "passive", groupLabel: "Пассивный доход и финансы", symbol: "tile-crypto", color: "#2F6B74", colorDark: "#1E4C52", kind: "income" },
  { key: "trading", label: "Биржа", group: "passive", groupLabel: "Пассивный доход и финансы", symbol: "tile-trading", color: "#2F6B74", colorDark: "#1E4C52", kind: "income" },
  { key: "rent-housing-income", label: "Аренда жилья", group: "rental", groupLabel: "Аренда и недвижимость", symbol: "tile-rent-housing-income", color: "#8A7F38", colorDark: "#696126", kind: "income" },
  { key: "rent-items-income", label: "Аренда вещей", group: "rental", groupLabel: "Аренда и недвижимость", symbol: "tile-rent-items-income", color: "#8A7F38", colorDark: "#696126", kind: "income" },
  { key: "cashback", label: "Кэшбэк", group: "refunds", groupLabel: "Возвраты и компенсации", symbol: "tile-cashback", color: "#3F8D5C", colorDark: "#2C6D44", kind: "income" },
  { key: "tax-refund", label: "Возврат налога", group: "refunds", groupLabel: "Возвраты и компенсации", symbol: "tile-tax-refund", color: "#3F8D5C", colorDark: "#2C6D44", kind: "income" },
  { key: "insurance-payout", label: "Страховая выплата", group: "refunds", groupLabel: "Возвраты и компенсации", symbol: "tile-insurance-payout", color: "#3F8D5C", colorDark: "#2C6D44", kind: "income" },
  { key: "employer-compensation", label: "Компенсация от работодателя", group: "refunds", groupLabel: "Возвраты и компенсации", symbol: "tile-employer-compensation", color: "#3F8D5C", colorDark: "#2C6D44", kind: "income" },
  { key: "overpayment-refund", label: "Возврат переплаты", group: "refunds", groupLabel: "Возвраты и компенсации", symbol: "tile-overpayment-refund", color: "#3F8D5C", colorDark: "#2C6D44", kind: "income" },
  { key: "pension", label: "Пенсия", group: "social", groupLabel: "Социальные выплаты и помощь", symbol: "tile-pension", color: "#478575", colorDark: "#32675A", kind: "income" },
  { key: "unemployment-benefit", label: "Пособие по безработице", group: "social", groupLabel: "Социальные выплаты и помощь", symbol: "tile-unemployment-benefit", color: "#478575", colorDark: "#32675A", kind: "income" },
  { key: "alimony", label: "Алименты", group: "social", groupLabel: "Социальные выплаты и помощь", symbol: "tile-alimony", color: "#478575", colorDark: "#32675A", kind: "income" },
  { key: "maternity-benefits", label: "Материнский капитал / Детские пособия", group: "social", groupLabel: "Социальные выплаты и помощь", symbol: "tile-maternity-benefits", color: "#478575", colorDark: "#32675A", kind: "income" },
  { key: "subsidies", label: "Субсидии", group: "social", groupLabel: "Социальные выплаты и помощь", symbol: "tile-subsidies", color: "#478575", colorDark: "#32675A", kind: "income" },
  { key: "gift-income", label: "Подарок", group: "windfall", groupLabel: "Разовые и случайные доходы", symbol: "tile-gift-income", color: "#A66B30", colorDark: "#835221", kind: "income" },
  { key: "lucky-find", label: "Находка", group: "windfall", groupLabel: "Разовые и случайные доходы", symbol: "tile-lucky-find", color: "#A66B30", colorDark: "#835221", kind: "income" },
  { key: "winnings", label: "Выигрыш", group: "windfall", groupLabel: "Разовые и случайные доходы", symbol: "tile-winnings", color: "#A66B30", colorDark: "#835221", kind: "income" },
  { key: "debt-repayment", label: "Долг", group: "windfall", groupLabel: "Разовые и случайные доходы", symbol: "tile-debt-repayment", color: "#A66B30", colorDark: "#835221", kind: "income" },
  { key: "own-account-transfer", label: "Перевод с другого своего счёта", group: "transfers", groupLabel: "Перемещение собственных средств", symbol: "tile-own-account-transfer", color: "#586674", colorDark: "#3E4C5B", kind: "income" },
  { key: "family-transfer", label: "Перевод от семьи", group: "transfers", groupLabel: "Перемещение собственных средств", symbol: "tile-family-transfer", color: "#586674", colorDark: "#3E4C5B", kind: "income" },
  { key: "scrap-recycling", label: "Сдача металлолома / макулатуры", group: "misc_income", groupLabel: "Дополнительные мелкие поступления", symbol: "tile-scrap-recycling", color: "#6D7F39", colorDark: "#515F26", kind: "income" },
  { key: "hobby-income", label: "Доход от хобби", group: "misc_income", groupLabel: "Дополнительные мелкие поступления", symbol: "tile-hobby-income", color: "#6D7F39", colorDark: "#515F26", kind: "income" },
  { key: "loan-interest-received", label: "Проценты по займам", group: "misc_income", groupLabel: "Дополнительные мелкие поступления", symbol: "tile-loan-interest-received", color: "#6D7F39", colorDark: "#515F26", kind: "income" },
];

const BY_KEY = new Map(CATEGORY_ICONS.map((i) => [i.key, i]));
export function iconByKey(key) { return BY_KEY.get(key) || null; }

// Иконки одного типа (для банка выбора в редакторе категории).
export function iconsByType(type) { return CATEGORY_ICONS.filter((i) => i.kind === type); }

// Осталось для однократной обратной миграции старых PNG-иконок (v1.30).
export const CATEGORY_ICON_DIR = "icons/categories/";
export function isBuiltinIcon(image) {
  return typeof image === "string" && image.indexOf(CATEGORY_ICON_DIR) === 0;
}
